name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build core
      run: make

    - name: Build unit tests for minheap
      run: cd unit_tests/minheap/ && make -f minheap_test.mk

    - name: Build unit tests for burst prediction
      run: cd unit_tests/burst_prediction/ && make -f burst_prediction_test.mk

    - name: Build unit tests for non-preemptive sjf scheduler
      run: cd unit_tests/non_preemptive_sjf/ && make -f nprmptv_sjf_test.mk
      
    - name: Upload unit tests build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: unit_test_artifact
        path: unit_tests
  tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Removing unit_tests folder
      run: rm -rf unit_tests
    
    - uses: actions/download-artifact@master
      with:
        name: unit_test_artifact
        path: unit_tests
    
    - name: enable execution permission of minheap artifacts
      run: chmod +x unit_tests/minheap/*.out

    - name: enable execution permission of burst prediction artifacts
      run: chmod +x unit_tests/burst_prediction/*.out

    - name: enable execution permission of non-preemptive sjf scheduler artifacts
      run: chmod +x unit_tests/non_preemptive_sjf/*.out

    - name: Run unit tests for minheap with generics
      run: cd unit_tests/minheap && ./test_with_generics.out

    - name: Run unit tests for minheap with specialised types
      run: cd unit_tests/minheap && ./test_with_specialised.out

    - name: Run unit tests for burst prediction
      run: cd unit_tests/burst_prediction && ./burst_prediction_test.out

    - name: Run unit tests for non-preemptive sjf scheduler
      run: cd unit_tests/non_preemptive_sjf && ./nprmptv_sjf_test.out
