name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build core
      run: make

    - name: Build unit tests for minheap
      run: make -f unit_tests/minheap/minheap_test.mk

  tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run unit tests for minheap with generics
      run: ./unit_tests/minheap/test_with_generics.out
