name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build core
      run: make

    - name: Build unit tests for minheap
      run: cd unit_tests/minheap/ && make -f minheap_test.mk
      
    - name: Upload minheap unit tests build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: minheap_unit_test_artifact
        path: unit_tests/minheap/test_with_generics.out

  tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@master
      with:
        name: minheap_unit_test_artifact
        path: unit_tests/minheap/
    
    - name: enable execution permission of artifcat
      run: chmod +x unit_tests/minheap/test_with_generics.out

    - name: Run unit tests for minheap with generics
      run: ./unit_tests/minheap/test_with_generics.out