name: Valgrind testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build core
      run: make

    - name: Build unit tests for minheap
      run: cd unit_tests/minheap/ && make -f minheap_test.mk

    - name: Build unit tests for burst prediction
      run: cd unit_tests/burst_prediction/ && make -f burst_prediction_test.mk

    - name: Build unit tests for non-preemptive sjf scheduler
      run: cd unit_tests/non_preemptive_sjf/ && make -f nprmptv_sjf_test.mk

    - name: Build unit tests for preemptive sjf scheduler
      run: cd unit_tests/preemptive_sjf/ && make -f prmptv_sjf_test.mk

    - name: Build unit tests for multi cpu scheduler
      run: cd unit_tests/multi_cpu/ && make -f multi_cpu_test.mk
      
    - name: Upload unit tests build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: unit_test_artifact
        path: unit_tests

  tests:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@master
      with:
        name: unit_test_artifact
        path: unit_tests

    - name: install valgrind
      run: sudo apt-get install valgrind -y

    - name: enable execution permission of minheap artifacts
      run: chmod +x unit_tests/minheap/*.out && chmod +x unit_tests/minheap/*.sh

    - name: enable execution permission of burst prediction artifacts
      run: chmod +x unit_tests/burst_prediction/*.out && chmod +x unit_tests/burst_prediction/*.sh

    - name: enable execution permission of non-preemptive sjf artifacts
      run: chmod +x unit_tests/non_preemptive_sjf/*.out && chmod +x unit_tests/non_preemptive_sjf/*.sh
    
    - name: enable execution permission of preemptive sjf artifacts
      run: chmod +x unit_tests/preemptive_sjf/*.out && chmod +x unit_tests/preemptive_sjf/*.sh

    - name: enable execution permission of multi cpu artifacts
      run: chmod +x unit_tests/multi_cpu/*.out && chmod +x unit_tests/multi_cpu/*.sh

    - name: Run minheap test
      run: cd unit_tests/minheap/ && ./valgrind_test.sh

    - name: Run burst prediction test
      run: cd unit_tests/burst_prediction/ && ./valgrind_test.sh

    - name: Run non-preemptive sjf test
      run: cd unit_tests/non_preemptive_sjf/ && ./valgrind_test.sh

    - name: Run preemptive sjf test
      run: cd unit_tests/preemptive_sjf/ && ./valgrind_test.sh

    - name: Run multi cpu test
      run: cd unit_tests/multi_cpu/ && ./valgrind_test.sh